extends Node3D

# The crooked house (south-west of the house, off the garden gate). Its shell
# (walls, roof, furniture, collision) is generated by tools/crooked_house_build.gd;
# this wrapper adds what can be played with and snaps it to the shell's markers
# so a rebuilt shell never leaves the zombie standing in a wall.
# Serious mode (owner, 2026-10-02) has no Angry Zombie and no tiny curse: the
# old zombie robot sits in his place, and gives what Silly hides behind the
# wardrobe's mouse hole (the sun tracker), so that pickup goes.

const ZOMBIE_ROBOT := preload("res://scenes/npc/zombie_robot.tscn")

@onready var shell: Node3D = $Shell
@onready var candle: OmniLight3D = $CandleLight

var _time := 0.0

func _ready() -> void:
	var resident: Node3D = $AngryZombie
	if Game.serious():
		var robot: Node3D = ZOMBIE_ROBOT.instantiate()
		robot.transform = resident.transform
		resident.free()
		$SunTracker.free()
		add_child(robot)
		resident = robot
	_snap(resident, "ZombieSpot")
	_snap($SolarCell, "ShelfTop")
	_snap(get_node_or_null("SunTracker"), "NookCentre")
	_snap($RoomLight, "RoomLight")
	_snap(candle, "Candle")
	_snap($ChimneySmoke, "ChimneyTop")
	_snap($YardTrigger, "DoorOutside")

func _process(delta: float) -> void:
	_time += delta
	candle.light_energy = 0.7 + 0.18 * sin(_time * 13.0) * sin(_time * 7.3 + 1.0)

func _snap(node: Node3D, marker: String) -> void:
	var m: Node3D = shell.get_node_or_null(marker)
	if node != null and m != null:
		node.position = m.position
